### ISSUE TITLE
please dockerize this project

### ISSUE THREAD

**Issue by amniati** [nekinci/container-service#1]
Hi Niyazi Ekinci,
please dockerize this project using dockerfile on root ,
waiting for your commit changes :)
finest regards

**Comment by nekinci** [comment]
Hi,
I dockerize the project. And I added `docker-compose.yml` file. You should run  `docker-compose.yml` command on the terminal. 
Also, You can run each of the frontend and backend service separately.  


`docker run -it -e MONGO_CONN_STRING=<your conn string> -e HOST=172.17.0.1 -v /var/run/docker.sock:/var/run/docker.sock -p 80:80 -p 8070:8070 <builded-image-name>   
`

` docker run -e HOST_ENV=DEV -p 3000:3000 <builded-frontend-image>`

Frontend dockerfile is under resources folder.

Happy hacking :)
